# app/config/security.yml

security:
    encoders:
        SIV\UsersBundle\Entity\Users: sha512

    providers:
        main:
            id: fos_user.user_provider.username
    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_SECURITY: [ROLE_SECURITY]
        ROLE_EMPLOYEE: [ROLE_EMPLOYEE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
              login_path: /login
              check_path: /login_check
              success_handler: redirect.after.login
            logout:
              path: /logout
              target: /
              success_handler: redirect.after.logout
               # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/employe, role: ROLE_EMPLOYEE }
        - { path: ^/securite, role: ROLE_SECURITY }
        - { path: ^/administration, role: ROLE_ADMIN }

