# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    fos_user.doctrine_registry:
        alias: doctrine
    redirect.after.login:
      class: SIV\UsersBundle\Redirection\AfterLoginRedirection
      arguments: [@router]

    redirect.after.logout:
      class: SIV\UsersBundle\Redirection\AfterLogoutRedirection
      arguments: [@router, @security.context]

    fos_message.driver:
      class: FOS\Message\Driver\Doctrine\ORM\DoctrineORMDriver
      arguments: [ "@doctrine.orm.entity_manager" ]

